{% set name = "nelson-siegel-svensson" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nelson_siegel_svensson-{{ version }}.tar.gz
  sha256: cc1ed8ba0d12f236490da5bc5eadf846e0baeb92f4935223cc99dfbd44c018e2

build:
  entry_points:
    - nelson_siegel_svensson=nelson_siegel_svensson.cli:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=6.0
    - matplotlib-base >=3.0
    - numpy >=1.14
    - python >={{ python_min }}
    - scipy >=1.2

test:
  imports:
    - nelson_siegel_svensson
  commands:
    - pip check
    - nelson_siegel_svensson --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/luphord/nelson_siegel_svensson
  summary: Implementation of the Nelson-Siegel-Svensson interest rate curve model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atrawog
    - wolfv
